version: '2'

services:
  mongodb:
    image: mongo:7.0.4
    container_name: 'telegramBot_db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PWD}
    volumes:
      - ./mongo/mongo_init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_volume:/data/db

  server:
    build:
      context: ./server/
    container_name: 'telegramBot_server'
    ports:
      - ${SERVER_PORTS}
    env_file:
      - .env
    depends_on:
      - mongodb

  admin_panel:
    build:
      context: ./admin_panel/
    container_name: 'telegramBot_frontend'
    ports:
      - ${FRONTEND_PORTS}
#    volumes:
#      - ./admin_panel:/app/admin_panel
#      - ./app/admin_panel/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - server
      - mongodb

volumes:
  mongo_volume: