version: '2'

services:
  mongodb:
    image: mongo:7.0.4
    container_name: 'telegramBot_db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PWD}
    volumes:
      - ./mongo/mongo_init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_volume:/data/db

  server:
    build:
      context: ./server
    container_name: 'telegramBot_server'
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    volumes:
      - ./server:/app/server
    depends_on:
      - mongodb

  admin_panel:
    build:
      context: ./admin_panel/
    container_name: 'telegramBot_frontend'
    ports:
      - "127.0.0.1:3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - server
      - mongodb

  bot:
    build:
      context: ./bot
    container_name: 'telegramBot_bot'
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot
    restart: always
    depends_on:
      - mongodb
      - server
      - admin_panel

volumes:
  mongo_volume: