version: '2'

services:
  mongodb:
    image: mongo:latest
    container_name: 'telegramBot_db'
    ports:
      - ${DB_PORTS}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PWD}
    volumes:
      - ./mongo/mongo_init.js:/docker-entrypoint-initdb.d/mongo-init.js